apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-2
  description: Python app that displays time - name python-app-2
  annotations:
    github.com/project-slug: scortellino/python-app-2
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: developer
  lifecycle: experimental
